#!/usr/bin/env python3
"""Generate a ProximityTrial.world variant for a specific battery condition:
static (fixed pivot, no motion) or moving (approach/retreat cycle, arbitrary pivot).

Used to produce the 2026-09-25 Proximity Stop trial battery reported in
paper2_draft.tex Section 6.1 (raw data: docs/data/proximity_stop_*.jsonl,
figures regenerated by docs/figures/make_plots.py). The three final,
verified world files this generated are checked in directly under
sara_gazebo/worlds/: ProximityTrial_static_A.world (pivot=0.306, near-edge
~0.20-0.22m from the lidar), ProximityTrial_static_B.world (pivot=0.346,
~0.23-0.26m), ProximityTrial_boundary.world (pivot=0.406, ~0.27-0.30m, at
the zone's own 0.3m outer edge). Re-run this script only if you need a
different pivot; the near-edge distance a given pivot actually produces
does not map 1:1 from simple geometry (confirmed empirically - a naive
pivot_x - radius - lidar_x calculation was off by enough to mislabel an
entire condition once, see the pivot-math postmortem in the
sara_paper2_framework memory) - always verify a new pivot's real detected
range live (`ros2 topic echo /proximity_nearest_range_m`) before trusting
it for a trial, don't just trust the arithmetic.

The moving condition (used for the "Moving, approach/retreat" row of the
battery, and for fig_proximity_stop_response.png's time series) is the
original ProximityTrial.world, not a file this script produced - kept as
the walking-actor world, unaffected by the static/boundary pivot work.
"""
import sys

HEADER = """<?xml version="1.0" ?>
<sdf version='1.7'>
  <world name='default'>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"></plugin>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"></plugin>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"></plugin>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"></plugin>

    <light name='sun' type='directional'>
      <cast_shadows>1</cast_shadows>
      <pose>0 0 10 0 -0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation><range>1000</range><constant>0.9</constant><linear>0.01</linear><quadratic>0.001</quadratic></attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name='ground_plane'>
      <static>1</static>
      <link name='link'>
        <collision name='collision'>
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface>
        </collision>
        <visual name='visual'>
          <cast_shadows>0</cast_shadows>
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <material><ambient>0.3 0.3 0.3 1</ambient><diffuse>0.7 0.7 0.7 1</diffuse><specular>0.01 0.01 0.01 1</specular></material>
        </visual>
      </link>
    </model>

    <actor name='human_actor'>
      <link name='link'>
        <visual name='body_visual'>
          <geometry><cylinder><radius>0.15</radius><length>1.5</length></cylinder></geometry>
          <material><ambient>0.8 0.4 0.1 1</ambient><diffuse>0.8 0.4 0.1 1</diffuse></material>
        </visual>
        <visual name='head_visual'>
          <pose>0 0 0.87 0 0 0</pose>
          <geometry><sphere><radius>0.12</radius></sphere></geometry>
          <material><ambient>0.8 0.6 0.4 1</ambient><diffuse>0.8 0.6 0.4 1</diffuse></material>
        </visual>
      </link>
      <script>
        <loop>true</loop>
        <delay_start>0.0</delay_start>
        <auto_start>true</auto_start>
        <trajectory id='0' type='walk' tension='1'>
{waypoints}
        </trajectory>
      </script>
    </actor>

    <gravity>0 0 -9.8</gravity>
    <magnetic_field>6e-06 2.3e-05 -4.2e-05</magnetic_field>
    <atmosphere type='adiabatic'/>
    <physics type='ode'>
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1</real_time_factor>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>
    <scene><ambient>0.4 0.4 0.4 1</ambient><background>0.7 0.7 0.7 1</background><shadows>1</shadows></scene>
    <spherical_coordinates><surface_model>EARTH_WGS84</surface_model><latitude_deg>0</latitude_deg><longitude_deg>0</longitude_deg><elevation>0</elevation><heading_deg>0</heading_deg></spherical_coordinates>
  </world>
</sdf>
"""


def wp(t, x, z=0.75):
    return f"          <waypoint><time>{t:.3f}</time><pose>{x} 0 {z} 0 0 0</pose></waypoint>"


def static_world(pivot_x, hold_s=20.0):
    waypoints = "\n".join([wp(0.0, pivot_x), wp(hold_s, pivot_x)])
    return HEADER.format(waypoints=waypoints)


def moving_world(pivot_x, far_x=3.0, speed=1.4, pause_s=1.0):
    leg = abs(far_x - pivot_x) / speed
    t0 = 0.0
    t1 = leg
    t2 = t1 + pause_s
    t3 = t2 + leg
    t4 = t3 + pause_s
    waypoints = "\n".join([
        wp(t0, far_x), wp(t1, pivot_x), wp(t2, pivot_x), wp(t3, far_x), wp(t4, far_x),
    ])
    return HEADER.format(waypoints=waypoints)


if __name__ == "__main__":
    mode = sys.argv[1]
    pivot = float(sys.argv[2])
    out = sys.argv[3]
    if mode == "static":
        hold = float(sys.argv[4]) if len(sys.argv) > 4 else 20.0
        content = static_world(pivot, hold)
    elif mode == "moving":
        content = moving_world(pivot)
    else:
        raise SystemExit("mode must be static or moving")
    with open(out, "w") as f:
        f.write(content)
    print(f"wrote {out}")
